version: '2' 
services: 
  storage:  
    build: laravel-storage
    volumes:
      - ../:/data
    restart: always

  database:  
    build: laravel-database
    volumes_from:
      - storage
    ports:
      - "3306:3306"
    restart: always

  phpfpm:  
    build: laravel-phpfpm
    volumes_from:
      - storage
    links:
      - database:database
    restart: always

  nginx:  
    build: laravel-nginx
    volumes_from:
      - storage
    links:
      - phpfpm:phpfpm
    depends_on:
      - database
      - phpfpm      
    ports:
      - "80:80"
    restart: always

  artisan:  
    build: laravel-artisan
    volumes_from:
      - storage
    depends_on:
      - database
      - phpfpm
      - nginx    
    links:
      - database:database

  composer:  
    build: laravel-composer
    volumes_from:
      - storage
    depends_on:
      - database
      - phpfpm
      - nginx

  # gulp:  
  #   build: laravel-gulp
  #   volumes_from:
  #     - storage    
