#!/usr/bin/env bash

if [ ! "$(command -v sudo docker docker-compose | wc -l)" -eq "3" ]; then

	cat <<-EOF

	Please install sudo, docker and docker-compose.

	Run it as root:

		apt-get install -y sudo 
		usermod -aG sudo <user>

		wget -qO- https://get.docker.com/ | sh
		usermod -aG docker <user>

		apt-get install -y python-pip
		pip install docker-compose

	EOF

	exit 1;
fi

DIR="$(dirname ${0})"

case "${1}" in
	artisan|composer)
		docker-compose -f ${DIR}/docker/docker-compose.yml run $@
		;;
	*)
		docker-compose -f ${DIR}/docker/docker-compose.yml $@
		;;
esac

